# Generated by Django 4.2.11 on 2025-06-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_about_profile_name_remove_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressf',
            name='phonenum',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
