# Generated by Django 4.2.11 on 2025-06-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='orders',
        ),
    ]
