# Generated by Django 4.2.11 on 2025-06-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_orders_est_delivert_orders_payment_id_orders_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='est_delivert',
            new_name='est_delivery',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_tracking',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
