# Generated by Django 4.2.11 on 2025-06-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_est_delivert_orders_est_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressf',
            old_name='hourseNo',
            new_name='houseNo',
        ),
    ]
