# Generated by Django 4.2.11 on 2025-06-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_addressf_address_alter_addressf_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('payment pending', 'Payment Pending'), ('processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('returned', 'returned'), ('replaced', 'replaced')], default='payment pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(blank=True, choices=[('order', 'order'), ('return', 'return'), ('replace', 'replace'), ('cancel', 'cancel')], default='order', max_length=255),
        ),
    ]
