# Generated by Django 4.2.11 on 2025-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Odate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='est_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
