# Generated by Django 4.2.11 on 2025-06-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_orders_odate_alter_orders_est_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Odate',
            field=models.DateField(auto_now=True),
        ),
    ]
