# Generated by Django 4.2.11 on 2025-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_orders_odate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Odate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
