# Generated by Django 4.2.11 on 2025-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_orders_odate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='est_delivery',
        ),
        migrations.AddField(
            model_name='orders',
            name='est_dates',
            field=models.JSONField(null=True),
        ),
    ]
