# Generated by Django 4.2.11 on 2025-06-05 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='session_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
