# Generated by Django 4.2.11 on 2025-06-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_orders_est_delivery_orders_est_dates'),
        ('shop', '0008_coupons_couponusages'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusages',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='couponusages',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.orders'),
        ),
    ]
