# Generated by Django 4.2.11 on 2025-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_couponusages_discount_couponusages_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ManyToManyField(blank=True, to='shop.brands'),
        ),
    ]
