# Generated by Django 4.2.11 on 2025-06-12 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_remove_products_brand_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='name',
        ),
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
        ),
    ]
