# Generated by Django 4.2.11 on 2025-06-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_ratings_name_ratings_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
