# Generated by Django 4.2.11 on 2025-06-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_ratings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
