# Generated by Django 4.2.11 on 2025-06-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_products_brand_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
        migrations.AlterField(
            model_name='ratings',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shop.products'),
        ),
    ]
