# Generated by Django 4.2.11 on 2025-06-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_products_rating_alter_ratings_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
