# Generated by Django 4.2.11 on 2025-06-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_orderitem_color_orderitem_size'),
        ('shop', '0016_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='orderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.orderitem'),
        ),
    ]
