# Generated by Django 5.2.4 on 2025-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_ratings_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ManyToManyField(blank=True, to='shop.brands'),
        ),
    ]
