# Generated by Django 5.2.4 on 2025-07-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_products_brand_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='category',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='category',
        ),
        migrations.AddField(
            model_name='brands',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.category'),
        ),
        migrations.AddField(
            model_name='colors',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.category'),
        ),
    ]
